### ISSUE TITLE
Placeholder field of age on register page broken

### ISSUE THREAD

**Issue by deevroman** [exsandebest/danchat#1]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0
<img width="363" alt="Снимок экрана 2020-01-20 в 17 35 01" src="https://user-images.githubusercontent.com/25708359/72735011-0acf6880-3bac-11ea-831b-bf302e7920f3.png">

**Comment by exsandebest** [comment]
The app is not cross-browser, but we will try to fix it
